#!/bin/sh

cdev="cua."
tdev="tty."
#IFS="|"

things[0]="A800HGEI|databee"

DEVCLASS=$1
DEVNAME=$2

case $DEVCLASS in
5)
	# tty thing
	for i in ${things[@]};
	do
		driver=
		IFS="|"
		set -A thing $i
		serial=${thing[0]}
		cname=$cdev${thing[1]}
		tname=$tdev${thing[1]}
		driver=$(usbdevs -dv | grep -A1 $serial | grep -v $serial | tr -s " ")
		cfndev="/dev/$cname"
		tfndev="/dev/$tname"
		if [[ -n $driver ]]; then
			logger -i "detach: usb-serial thing not in list"
		else
			rm $cfndev
			rm $tfndev
			logger -i "detach: $cfndev removed"
			logger -i "detach: $tfndev removed"
		fi
	done
;;
esac

exit 0
