.\"
.\" Copyright (c) 2016-2019 Tracey Emery <tracey@traceyemery.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: December 19 2018 $
.Dt THINGSD 8
.Os
.Sh NAME
.Nm thingsd
.Nd things OpenBSD proxy daemon
.Sh SYNOPSIS
.Nm thingsd
.Bk -words
.Op Fl dv
.Ek
.Sh DESCRIPTION
The
.Nm
OpenBSD proxy daemon provides a mechanism for clients and client
processes to communicate with an array of serial and IoT things.
At its core,
.Nm
is primarily a data aggregator and repeater, in that it waits for
packets to swap between subscriber clients and things.
However,
.Nm
also provides TLS and password control over those connections, including
client limits.
.Pp
On the client side,
.Nm
sets up TCP/IP sockets to transmit packets to and from things.
On the server side,
.Nm
can connect to any serial device which has a viable file descriptor, create a
persistent connection to the IP address of a device transmitting packets,
or setup a UDP listener on the network to receive broadcasted packets.
Devices tested include: ESP8266/ESP32 modules, on both the serial and network
sides, XBee Series 2 coordinators connected in a mesh network, and NF24
devices.
To transmit to an IP address, which does not allow persistence,
.Nm
will create an ad hoc connection, transmit a packet, and detach.
The
.Nm
proxy daemon is agnostic about packet data.
.Pp
The options are as follows:
.Bl -tag -width "-f fileXXX"
.It Fl d
Do not daemonize.
If this option is specified,
.Nm
will run in the foreground and log to
.Em stderr .
.It Fl v
This option allows
.Nm
to send DEBUG priority messages to syslog.
.El
.Pp
Subscribers to a thing pass a simple, human-readable packet to
.Nm .
The format is as follows, without the line breaks and tabs.
This example is only for initial readability and help in understanding
the format!
.Pp
Subscription packets must begin with 3 * 0x7E
.Bd -literal -offset indent
~~~subscribe{
	{name,"CLIENTNAME"},
	{things{
		thing{"dev1","pass"},
		thing{"dev2","pass"}
		}
	}
}
.Ed
.Pp
An accurate packet would not include linebreaks.
.Pp
.Nm
is usually started at boot time, and can be enabled by adding
.Nm
to the
.Va pkg_scripts
line in
.Pa /etc/rc.conf.local .
See
.Xr rc 8
and
.Xr rc.conf 8
for more information on the boot process and enabling daemons.
.Pp
When
.Nm
starts up, it reads settings from its configuration file, typically
.Xr thingsd.conf 5 ,
and creates sockets and file descriptor connections.
.Sh FILES
.Bl -tag -width "/var/run/thingsdd.sockXXX" -compact
.It Pa /etc/thingsd.conf
Default configuration file.
.It Pa /var/run/thingsd.sock
Socket file for communication with
.Xr thingsctl 8 .
.El
.Sh SEE ALSO
.Xr thingsd.conf 5 ,
.Xr rc 8 ,
.Xr rc.conf 8 ,
.Xr thingsctl 8
.Sh HISTORY
The busybeed program first began development on
.Ox 5.9 . The
.Nm
program refactoring and rename began on
.Ox 6.4 . thingsd name by Matthew Graybosch .
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An Tracey Emery Aq Mt tracey@traceyemery.net .
