.\"
.\" Copyright (c) 2016-2019 Tracey Emery <tracey@traceyemery.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: December 19 2018 $
.Dt THINGSD.CONF 5
.Os
.Sh NAME
.Nm thingsd.conf
.Nd thingsd OpenBSD proxy daemon configuration file
.Sh DESCRIPTION
.Nm
is the configuration file for the things proxy daemon,
.Xr thingsd 8 .
.Sh SECTIONS
.Nm
is divided into two main sections:
.Bl -tag -width xxxx
.It Sy Global Configuration
Global settings for
.Xr thingsd 8 .
Do note that global settings should never be placed after the things section
has been defined.
.It Sy things
things are the configuration areas for each thing a client can communicate
with.
.El
.Pp
The current line can be extended over multiple lines using a backslash
.Pq Sq \e .
Comments can be put anywhere in the file using a hash mark
.Pq Sq # ,
and extend to the end of the current line.
Care should be taken when commenting out multi-line text:
the comment is effective until the end of the entire block.
.Pp
Argument names not beginning with a letter, digit, or underscore
must be quoted.
.Sh GLOBAL CONFIGURATION
Here are the settings that can be set globally:
.Bl -tag -width Ds
.It Ic bind tcp interface Ar string
Specify a single interface to create client listening sockets on.
If this is not set,
.Xr thingsd 8
will attempt to open thing assigned
.Ar listen
ports on all network interfaces.
.It Ic bind udp interface Ar string
Specify a single interface to create UDP receive sockets on.
If this is not set, it is required to set the interface per UDP thing.
.It Ic connection retry Ar number
Set the lost connection thing watchdog interval.
Default is 30 seconds.
Range is 30-600 seconds.
.It Ic max clients Ar number
Set the default maximum number of clients allowed to connect to each
.Xr thingsd 8 thing.
.It Ic prefork Ar number
Run the specified number of things processes.
This increases the performance and prevents delays when connecting to a thing.
.Xr thingsd 8
runs 3 things processes by default.
.El
.Sh THINGS
things represent a serial, TCP/IP, or UDP listener thing for
.Xr thingsd 8
to communicate with.
.Xr thingsd 8
will setup sockets and bind to things depending on the settings for each
thing.
.Bl -tag -width Ds
.It Ic baud Ar number
Set the baud rate for a serial thing
.Ar location .
.It Ic bind tcp interface Ar string
Specify a single interface to create a
.Ar location
or
.Ar ipaddr
thing socket.
.It Ic bind udp interface Ar string
Specify a single interface to create a
.Ar udp
receive socket for a thing.
.It Ic connect on port Ar number
Set the TCP/IP port to connect to for an
.Ar ipaddr
thing.
This setting is required for
.Ar ipaddr
things.
.It Ic data Ar number
Set the data bits for a serial thing
.Ar location .
.It Ic hardware Ar number
Set to 1 to turn on hardware control for a serial thing
.Ar location .
.It Ic ipaddr Ar string Brq ...
Create a
.Ar thing
connection to a hostname or IP address.
.It Ic listen on Oo Ic tls Oc port Ar number
Set a local socket port for a
.Ar location ,
.Ar udp ,
or
.Ar ipaddr
thing.
This setting is required and must be unique from other thing assigned listen
ports.
.It Ic location Ar string Brq ...
Create a
.Ar thing
connection to serial interface.
These are any valid /dev things, for example /dev/ttyU0.
Set the owner of a thing to _thingsd to allow for autoreconnect in
a privdrop environment, in the event of a serial thing disconnect.
.It Ic max clients Ar number
Set the maximum clients allowed to connect to a thing
.Ar location
or
.Ar ipaddr .
.It Ic parity Ar string
Set the parity for a serial thing
.Ar location .
Parity options are none, odd, even, or space.
.It Ic password Ar string
Set the subscription password for a thing
.Ar location
or
.Ar ipaddr  .
.It Ic persistent Ar number
Set whether
.Xr thingsd 8
binds to an
.Ar ipaddr
thing.
If
.Ar persistent
is set to 0,
.Xr thingsd 8
will create a socket, send a client packet, and close that socket.
Clients cannot receive on a non-persistent
.Ar ipaddr
thing.
.It Ic receive on port Ar number
Set the
.Ar udp
port to listen on for a UDP packet.
This setting is required for
.Ar udp
things and must be unique from other thing assigned UPD ports.
.It Ic software Ar number
Set to 1 to turn on software control for a serial thing
.Ar location .
.It Ic stop Ar number
Set the stop bit for a serial thing
.Ar location .
.It Ic thing Ar string Brq ...
Declaration of a thing for
.Xr thingsd 8
to setup and the name
.Xr thingsd 8
will use for client subscriptions.
.It Ic tls Ar option
Set the TLS configuration for a thing.
These options are only used if TLS has been enabled via the listen directive.
Valid options are:
.Bl -tag -width Ds
.It Ic certificate Ar file
Specify the certificate to use for this thing.
The
.Ar file
should contain a PEM encoded certificate.
The default is
.Pa /etc/ssl/thing.crt .
.It Ic ciphers Ar string
Specify the TLS cipher string.
If not specified, the default value
.Qq HIGH:!aNULL
will be used (strong crypto cipher suites without anonymous DH).
See the CIPHERS section of
.Xr openssl 1
for information about SSL/TLS cipher suites and preference lists.
.It Ic client ca Ar cafile Oo Ic crl Ar crlfile Oc Op Ic optional
Require
.Po
or, if
.Ic optional
is specified, request but do not require
.Pc
TLS client certificates whose authenticity can be verified
against the CA certificate(s) in
.Ar cafile
in order to proceed beyond the TLS handshake.
With
.Ic crl
specified, additionally require that no certificate in the client chain be
listed as revoked in the CRL(s) in
.Ar crlfile .
CA certificates and CRLs should be PEM encoded.
.It Ic dhe Ar params
Specify the DHE parameters to use for DHE cipher suites.
Valid parameter values are none, legacy and auto.
For legacy a fixed key length of 1024 bits is used, whereas for auto the key
length is determined automatically.
The default is none, which disables DHE cipher suites.
.It Ic ecdhe Ar curves
Specify a comma separated list of elliptic curves to use for ECDHE cipher suites,
in order of preference.
The special value of "default" will use the default curves; see
.Xr tls_config_set_ecdhecurves 3
for further details.
.It Ic key Ar file
Specify the private key to use for this thing.
The
.Ar file
should contain a PEM encoded private key and reside outside of the
.Xr chroot 2
root directory of
.Nm httpd .
The default is
.Pa /etc/ssl/private/thing.key .
.It Ic ocsp Ar file
Specify an OCSP response to be stapled during TLS handshakes
with this thing.
The
.Ar file
should contain a DER-format OCSP response retrieved from an
OCSP server for the
.Ar certificate
in use,
and can be created using
.Xr ocspcheck 8 .
The path to
.Ar file
is not relative to the chroot.
If the OCSP response in
.Ar file
is empty, OCSP stapling will not be used.
The default is to not use OCSP stapling.
.It Ic protocols Ar string
Specify the TLS protocols to enable for this thing.
If not specified, the value
.Qq default
will be used (secure protocols; TLSv1.2-only).
Refer to the
.Xr tls_config_parse_protocols 3
function for other valid protocol string values.
.El
.It Ic udp Ar string Brq ...
Create a
.Ar thing
which listens for user datagram protocol packets.
.El
.Sh FILES
.Bl -tag -width Ds -compact
.It Pa /etc/thingsd.conf
.Xr thingsd 8 configuration file.
.El
.Sh EXAMPLES
This configuration file would create a serial thing and a TCP/IP host thing.
.Bd -literal -offset indent

#
# Global Options
#

prefork 5

max clients 10

max suscriptions 5

thing "serial_thing" {
	location "/dev/ttyU0" {
		listen on tls port 50060
		baud 9600
		max clients 1
		data 8
		parity "none"
		stop 1
		tls certificate "/etc/ssl/my_thing.crt"
		tls key "/etc/ssl/private/my_thing.key"
		#no password required for our one allowed client
	}
}

thing "ipaddr_thing" {
	ipaddr "10.0.0.1" {
		connect on port 8080
		listen on port 50000
		password "password"
	}
}

thing "udp_thing" {
	udp "my_name" {
		receive on port 8095
		listen on port 50010
		password "password"
	}
}
.Ed
.Sh SEE ALSO
.Xr thingsctl 8 ,
.Xr thingsd 8
.Sh HISTORY
The
.Nm
file format first appeared with busybeed development on
.Ox 5.9 .
.Sh AUTHORS
.An -nosplit
The
.Xr thingsd 8
program was written by
.An Tracey Emery Aq Mt tracey@traceyemery.net .
